# Generated by ChatGPT
import re

RED = "\033[31m"
RESET = "\033[0m"

# Written by us
text = "Touching on education, allow me to briefly delve into UoA's unique undergraduate program. Our enrollment number is 240 per graduating class. That number may at first seem unimpressive. However, nurturing that many ICT conversant students each year is indeed unique in the field of information science in Japan and places us among the largest of all like-minded, informatics-leaned universities in Japan. We retain approximately 110 full-time faculty members. That means each faculty advisor's fair share is two to three students per graduating class. Such a low student-to-faculty ratio affords us the opportunity to provide our students with a complete package of individual lessons imparting knowledge and skills, followed up by caring and trusted mentoring to ensure students graduate with confidence in their abilities."

operation = input("Input things what to search: ")

if operation == 'Token':

    # Generated by ChatGPT
    target = input("Input the key words: ").strip().lower()

    original_words = re.findall(r"\b[\w']+[.,!?;:\"]*|\w+", text)

    cleaned_words = [re.sub(r"[.,!?;:\"]+$", "", word).lower() for word in original_words]

    target_words = target.split()
    phrase_len = len(target_words)

    found_indices = []
    for i in range(len(cleaned_words) - phrase_len + 1):
        if cleaned_words[i:i + phrase_len] == target_words:
            found_indices.append(i)

    if not found_indices:
        print("The key words is not found.")
    else:
        for index in found_indices:
            start = max(index - 5, 0)
            end = min(index + phrase_len + 5, len(original_words))

            context = (
                original_words[start:index] +
                [RED + ' '.join(original_words[index:index + phrase_len]) + RESET] +
                original_words[index + phrase_len:end]
            )

            print("... " + ' '.join(context) + " ...")

# Written by us
elif operation == 'POS':
    print(operation)
elif operation == 'Entity':
    print(operation)
else:
    print("Error!")